# NUMPY

In [1]:
list = [1,2,34,5]
list

[1, 2, 34, 5]

In [2]:
list[1]

2

we can run into problem using large set of data , mainly have varity of data like string , numerical ....having massive amount of data it will computational expensive , it will slower n  all 
instead of using list we use numpy for machine learning 
r

In [3]:
import numpy as np 
# Numpy is Numerical Python , it has to be of same datatype , it have n dimensions
np1 = np.array([0,1,2,3,4,5,6,7,8,9])
np1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np1.shape # lenght also 1D 

(10,)

In [5]:
np2 = np.arange(10)          #Range
print(np2)
np3 = np.arange(0,10,2)      #Step
print(np3)
np4 = np.zeros(10)           #zero
print(np4)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
#lets go multi dimensional 
np5 = np.zeros((2,10))
np5

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
#full for no. other than zero 
np6 = np.full((10),6)
print(np6)

# multi dimensional 
np7 = np.full((2,10),7)
np7

[6 6 6 6 6 6 6 6 6 6]


array([[7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7]])

In [8]:
# coverting list to numpy
print(list)
np8 = np.array(list)
print(np8)

[1, 2, 34, 5]
[ 1  2 34  5]


.
.
.
.
.
.
.


In [9]:
#Slicing Numpy array 
print(np1)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
np1[1:5]

array([1, 2, 3, 4])

In [11]:
np1[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [12]:
np1[:5]

array([0, 1, 2, 3, 4])

In [13]:
np1[-3:-1]

array([7, 8])

In [14]:
np1[-1:-3]

array([], dtype=int32)

In [15]:
np1[1:8:2]  #1 (2) 3 (4) 5 (6) 7 

array([1, 3, 5, 7])

In [16]:
np1[::2]

array([0, 2, 4, 6, 8])

In [17]:
np10 = np.full((2,5),2)
print(np10)

[[2 2 2 2 2]
 [2 2 2 2 2]]


In [18]:
np10 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

# pull out a single item 
print(np10[1,2])

#slice a 2d array
print(np10[0:1,1:3])

8
[[2 3]]


In [19]:
#slice BOTH 2d array
print(np10[0:2,1:3])   # the first one is dimension and another one it slicing we want to do

[[2 3]
 [7 8]]


In [20]:
# universal functions of Numpy 

In [21]:
print(np.sqrt(np1))


[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [22]:
np11 = np.array([-3,-2,-1,0,1,2,3])
print(np.absolute(np11))

[3 2 1 0 1 2 3]


In [23]:
np.exp(np1)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [24]:
np.min(np11)

-3

In [25]:
np.max(np11)

3

In [26]:
# copy vs view 


In [27]:
# import numpy as np
np1=np.array([0,2,3,4,5])

#create a view
np2 = np1.view()

print(f"Original NP1 {np1}")
print(f"Original NP2 {np2}")

np1[0] = 41

print(f"Changed NP1 {np1}")
print(f"Original NP2 {np2}")
    
    
# we can see in the output below that
# np1 was changed 
# but the np2 to which we didnt updated gets updated too
# thes esome main difference as in view its doesnt get changed np2 will as before thee is no connection 

Original NP1 [0 2 3 4 5]
Original NP2 [0 2 3 4 5]
Changed NP1 [41  2  3  4  5]
Original NP2 [41  2  3  4  5]


In [28]:
np1=np.array([0,2,3,4,5])
#create a copy
np2 = np1.copy()

print(f"Original NP1 {np1}")
print(f"Original NP2 {np2}")

np1[0] = 41

print(f"Changed NP1 {np1}")
print(f"Original NP2 {np2}")

Original NP1 [0 2 3 4 5]
Original NP2 [0 2 3 4 5]
Changed NP1 [41  2  3  4  5]
Original NP2 [0 2 3 4 5]


SHAPING AND RESHAPING YO\

In [29]:
import numpy as np 
np11 = np.array([1,2,3,4,5,6,7,8])
print(np11)
print(np11.shape)

np12= np.array([[1,2,3,4,5,6,7,8],[9,10,11,12,13,14,15,16]])
print(np12)
print(np12.shape)



[1 2 3 4 5 6 7 8]
(8,)
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
(2, 8)


In [30]:
# the real fun 
#Resphape 
np13 = np11.reshape(4,2)
print(np13)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [31]:
np14 = np11.reshape(3,3)
np14

ValueError: cannot reshape array of size 8 into shape (3,3)

# tip  the no. of these things , ixj matrix 

In [32]:
np15 = np11.reshape(1,1,8)
print(np15)

[[[1 2 3 4 5 6 7 8]]]


In [33]:
np15 = np11.reshape(8,1,1)
print(np15)

[[[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]

 [[6]]

 [[7]]

 [[8]]]


In [34]:
np11= np.array([1,2,3,4,5,6,7,8,9,0,1,2])
np15 = np11.reshape(3,4,1)
print(np15)

[[[1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]]

 [[9]
  [0]
  [1]
  [2]]]


In [35]:
np15 = np11.reshape(1,4,3)
print(np15)

[[[1 2 3]
  [4 5 6]
  [7 8 9]
  [0 1 2]]]


In [36]:
np15 = np11.reshape(1,3,4)
print(np15)

[[[1 2 3 4]
  [5 6 7 8]
  [9 0 1 2]]]


In [37]:
np15 = np11.reshape(3,2,2)
print(np15)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]

 [[9 0]
  [1 2]]]


In [38]:
#flatten to 1D
//np15 = np11.reshape(-1)
//print(np15)

SyntaxError: invalid syntax (1866441914.py, line 2)

iteration

In [39]:
for x in np11:
    print(x)


1
2
3
4
5
6
7
8
9
0
1
2


In [40]:
for x in np12:
    print(x)
    for y in x:
        print(y)


[1 2 3 4 5 6 7 8]
1
2
3
4
5
6
7
8
[ 9 10 11 12 13 14 15 16]
9
10
11
12
13
14
15
16


In [41]:
for x in np15:
    print(x)
    for y in x:
        print(y)
        for z in y:
            print(z)
        print()
    print()        

[[1 2]
 [3 4]]
[1 2]
1
2

[3 4]
3
4


[[5 6]
 [7 8]]
[5 6]
5
6

[7 8]
7
8


[[9 0]
 [1 2]]
[9 0]
9
0

[1 2]
1
2




In [42]:
for x in np15:
    #print(x)
    for y in x:
        #print(y)
        for z in y:
            print(z)
        #print()
    #print()        

1
2
3
4
5
6
7
8
9
0
1
2


In [43]:
# Use np.nditer()

for x in np.nditer(np15):
    print(x)

1
2
3
4
5
6
7
8
9
0
1
2


# lol f 


In [44]:
import numpy as np
#np.sort()
np1 = np.array([9,5,6.1,9,7,4,6.09,1])
print(np1)
print(np.sort(np1))

[9.   5.   6.1  9.   7.   4.   6.09 1.  ]
[1.   4.   5.   6.09 6.1  7.   9.   9.  ]


In [45]:
np1 = np.array(["adj","adji","aksht","hardi","ansh"])
print(np1)
print(np.sort(np1))

['adj' 'adji' 'aksht' 'hardi' 'ansh']
['adj' 'adji' 'aksht' 'ansh' 'hardi']


In [46]:
np1 = np.array([True,False,False,True])
print(np1)
print(np.sort(np1))

[ True False False  True]
[False False  True  True]


In [47]:
np1 = np.array([True,False,False,True,0,1,0,1])
print(np1)
print(np.sort(np1))

[1 0 0 1 0 1 0 1]
[0 0 0 0 1 1 1 1]


In [48]:
# return a copy without updating it 
np1 = np.array([9,5,6,1,9,7,4,6,9,1])
print(np1)
print(np.sort(np1))
print(np1)

[9 5 6 1 9 7 4 6 9 1]
[1 1 4 5 6 6 7 9 9 9]
[9 5 6 1 9 7 4 6 9 1]


In [49]:
np1= np.array([[1,8,2,3,4,8,5],[9,10,16,45,34,23,44]])
print(np1)
print()
print(np.sort(np1))

[[ 1  8  2  3  4  8  5]
 [ 9 10 16 45 34 23 44]]

[[ 1  2  3  4  5  8  8]
 [ 9 10 16 23 34 44 45]]


# SEARCHING THROUGH NUMPY ARRAY

In [50]:
np1 = np.array([1,2,3,4,5,6,7,7,7,9,10])
x   = np.where(np1 == 7)
print(x)

(array([6, 7, 8], dtype=int64),)


In [51]:
print(x[0])

[6 7 8]


In [52]:
print(np1[x[0]])

[7 7 7]


In [53]:
y = np.where(np1 % 2 == 0)
print(y)

(array([ 1,  3,  5, 10], dtype=int64),)


In [54]:
print(y[0])
print(np1[y[0]])

[ 1  3  5 10]
[ 2  4  6 10]


In [55]:
# filtering the numpy array 
np1 = np.array([1,2,3,4,5,6,7,7,7,9,10])
x = [True,True,False,False,False,False,False,False,False,False,False]
print(np1[x])


[1 2]


In [56]:
f1=[]
for i in np1:
    if i % 2 == 0:
        f1.append(True)
    else:
        f1.append(False)

print(np1)
print(f1)
print(np1[f1])

[ 1  2  3  4  5  6  7  7  7  9 10]
[False, True, False, True, False, True, False, False, False, False, True]
[ 2  4  6 10]


In [57]:
#shoeirucut 
np2 = np.array([1,2,3,4,5,6,7,7,7,9,10])
f2 = np2 % 2 == 0
print(np2)
print(f2)
print(np2[f2])

[ 1  2  3  4  5  6  7  7  7  9 10]
[False  True False  True False  True False False False False  True]
[ 2  4  6 10]


In [58]:
# the end